### ISSUE TITLE
Warnings Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by lucasfsousa** [lazy-actions/slatify#67]
Hi, 

I'm trying to integrate it on Github actions with the following template:

```
name: "Some name"
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: homoluctus/slatify@master
        with:
          type: ${{ job.status }}
          job_name: '*STAGE*'
          mention: 'here'
          mention_if: 'failure'
          channel: '#actions'
          url: ${{ secrets.SLACK_WEBHOOK }}
```

We have some warnings in the console:

```
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
Generated payload for slack: {"text":"Deploy lambdas to *STAGE* Succeeded","attachments":[{"color":"#2cbe4e","blocks":[{"type":"section","fields":[{"type":"mrkdwn","text":"*repository*\n<*>"},{"type":"mrkdwn","text":"*ref*\nrefs/heads/develop"},{"type":"mrkdwn","text":"*event name*\npush"},{"type":"mrkdwn","text":"*workflow*\n<*>"}]}]}],"unfurl_links":true}
(node:6475) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
