### ISSUE TITLE
Set emoji based on condition?

### ISSUE THREAD

**Issue by websocket98765** [lazy-actions/slatify#78]
Is there a way to include a specific emoji in the title base on success or fail?

I'd like to include a green emoji on success, or a red emoji on failure, for quicker recognition.

```
- name: Notify Slack on success or failure 
  uses: lazy-actions/slatify@master
  if: always() 
  with:
    url: ${{ secrets.SLACK_WEBHOOK_URL }}
    job_name: 'CI'
    type: ${{ job.status }}
    mention: 'channel'
```
